---
format: gfm
title: "Updating R and R Studio"
author: "Beth Jump"
date: "2025-06-12"
---

## Overview

It’s important to update both your R software and your R Studio IDE periodically. Updating your R software ensures that you're able to use the newest versions of packages that have been released and that your code and functions stay current and able to be shared easily. If you don't update your R software for a long time (>2-3 years) you might end up with code that is written that doesn't work on a current version of R.

You don't have to update R and R Studio at the same time. 

## Steps for updating R and R Studio

Updating R and R Studio involves downloading new versions of R and R Studio and installing the packages you need. If possible, you should do the steps in the order below as it will ensure that your new R Studio installation will look to your new R installation to run code from. 

1. Install a new version of R. 
    + You can download the newest version of R [here](https://cran.rstudio.com/). Just click the hyperlink at the top that says **Download R-4.X.X for Windows**.   
  
2. Install packages in your new version of R.
    + If you have admin rights you should do this in the actual R application because you can run it as an administrator and install packages directly onto the computer you're using. If you don't have admin rights, you can do this in the R or R Studio application.
    + To get to the R application go to C:\Program Files\R. Open the folder with your new installation of R (ex: R-4.5.0) and go to the **bin** folder. Right click on the **R.exe** application and run it as an administrator.  
    + We have a [script](https://github.com/San-Mateo-County-Health-Epidemiology/Helpful-Code-Bits/blob/main/R/packages-to-install-with-new-R-installation.R) with a running list of packages we commonly use that you should install when you get a new version of R. Please feel free to add any packages we've missed to this script!

3. Install new version of R Studio
    + Check Help > 
    + You need admin rights to do this 
    + https://posit.co/download/rstudio-desktop/

Note: R and R Studio updates aren’t released on the same schedule. It’s fine to do steps 1 and 2 at a different time than step 3. 
